### ISSUE TITLE
Add WMS support

### ISSUE THREAD

**Issue by turban** [dhis2/dhis2-gis-api#33]

**Comment by jason-p-pickering** [comment]
This is a long needed feature I have been looking for for years. Can you add WFS while you are at it?

In terms of persistence, is use of the app data store a potential option?

**Comment by turban** [comment]
Well WFS is much more complicated, as this is raw vector data that needs styling, interaction etc. Another option is GeoJSON support, which is now an [official standard](https://tools.ietf.org/html/rfc7946) and much easier to deal with in the browser - but we have the same issues with styling and interaction. 

Do you have a use case for including raw vector data in DHIS 2 @jason-p-pickering? 

> In terms of persistence, is use of the app data store a potential option?

https://github.com/dhis2/dhis2-gis/issues/149

**Comment by jason-p-pickering** [comment]
@turban: The use case is for vector layers, such as points, which may be stored in an external WFS and could be rendered with simplistic styling (often supplied by the server, such as GeoServer). Since they are vector points, they could contain interactive information  to the user. 

Other use cases are vector layers like roads which could be represented through default styling from the WFS. 

Agree it is non-trivial, and could have performance implications however.

**Comment by turban** [comment]
I think road networks could be included as a transparent WMS/TMS/XYZ layer. We will support all these formats from 2.25 - but they're all raster based. 

There is a [WFS plugin to Leaflet](https://github.com/Flexberry/Leaflet-WFST), but I'm not yet sure if it's the right way to go. 

An easier integration would be to support interactive tiles (UTFGrids) to get the same functionality as WFS, but without so much hassle.  UTFGrids are now supported by GeoServer: http://docs.geoserver.org/latest/en/user/services/wms/outputformats.html

**Comment by jason-p-pickering** [comment]
@turban fair enough. WMS is a great start. Lets keep the use case for WFS in mind a bit, but this is a great start.
